{
  "hash": "d0bd20a7b04c1838f635c5a8097cbda3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Near Infra-Red Spectroscopy Predicts Crude Protein in Hemp Grain\nexecute:\n  echo: false\nauthor:\n  - name: Ryan Crawford\n    # orcid: 0000-0002-0760-5497\n    corresponding: true\n    email: rvc3@cornell.edu\n    # roles:\n    #   - Investigation\n    #   - Project administration\n    #   - Software\n    #   - Visualization\n    affiliations:\n      - name: Cornell University\n        address: 126 Medicago Drive\n        city: Ithaca\n        state: NY\n        postal-code: 14853\n  - name: Jamie Crawford\n    # orcid: 0000-0002-0760-5497\n    corresponding: false\n    # roles:\n    #   - Investigation\n    #   - Project administration\n    #   - Software\n    #   - Visualization\n    affiliations:\n      - name: Cornell University\n        address: 126 Medicago Drive\n        city: Ithaca\n        state: NY\n        postal-code: 14853\n  - name: Lawrence B. Smart\n    # orcid: 0000-0002-7859-8394\n    corresponding: false\n    roles: []\n    affiliations:\n      - name: Cornell AgriTech\n        address: 102 Hedrick Hall\n        city: Geneva\n        state: NY\n        postal-code: 14456\n  - name: Virginia Moore\n    # orcid: 0000-0002-7859-8394\n    corresponding: false\n    roles: []\n    affiliations:\n      - name: Cornell University\n        address: 162 Emerson Hall\n        city: Ithaca\n        state: NY\n        postal-code: 14853    \nkeywords:\n  - Hemp\n  - Grain\n  - Spectroscopy\nabstract: |\n  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nplain-language-summary: |\n  Earthquake data for the island of La Palma from the September 2021 eruption is found ...\nkey-points:\n  - A web scraping script was developed to pull data from the Instituto Geogràphico Nacional into a machine-readable form for analysis\n  - Earthquake events on La Palma are consistent with the presence of both mantle and crustal reservoirs.\ndate: last-modified\nbibliography:\n  - references.bib\n  - grateful-refs.bib\n\n# bibliography: grateful-refs.bib\n  # - references.bib\n  # - grateful-refs.bib\n# csl: apa.csl\n# citation:\n#   container-title: Earth and Space Science\n# number-sections: true\n# bibliography: references.bib\n---\n\n::: {.cell .hidden}\n\n```{.r .cell-code .hidden}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.0     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(data.table)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'data.table'\n\nThe following objects are masked from 'package:lubridate':\n\n    hour, isoweek, mday, minute, month, quarter, second, wday, week,\n    yday, year\n\nThe following objects are masked from 'package:dplyr':\n\n    between, first, last\n\nThe following object is masked from 'package:purrr':\n\n    transpose\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(caret)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: lattice\n\nAttaching package: 'caret'\n\nThe following object is masked from 'package:purrr':\n\n    lift\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(prospectr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\u001b[34mprospectr version 0.2.7 -- cakes\u001b[39m\n\u001b[34mcheck the package repository at: https://github.com/l-ramirez-lopez/prospectr\u001b[39m\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(pls)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'pls'\n\nThe following object is masked from 'package:prospectr':\n\n    msc\n\nThe following object is masked from 'package:caret':\n\n    R2\n\nThe following object is masked from 'package:stats':\n\n    loadings\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(tidymodels)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Attaching packages ────────────────────────────────────── tidymodels 1.1.1 ──\n✔ broom        1.0.5      ✔ rsample      1.2.0 \n✔ dials        1.2.1      ✔ tune         1.1.2 \n✔ infer        1.0.6      ✔ workflows    1.1.4 \n✔ modeldata    1.3.0      ✔ workflowsets 1.0.1 \n✔ parsnip      1.2.0      ✔ yardstick    1.3.0 \n✔ recipes      1.0.10     \n── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──\n✖ data.table::between()    masks dplyr::between()\n✖ scales::discard()        masks purrr::discard()\n✖ dplyr::filter()          masks stats::filter()\n✖ data.table::first()      masks dplyr::first()\n✖ recipes::fixed()         masks stringr::fixed()\n✖ dplyr::lag()             masks stats::lag()\n✖ data.table::last()       masks dplyr::last()\n✖ caret::lift()            masks purrr::lift()\n✖ yardstick::precision()   masks caret::precision()\n✖ yardstick::recall()      masks caret::recall()\n✖ yardstick::sensitivity() masks caret::sensitivity()\n✖ yardstick::spec()        masks readr::spec()\n✖ yardstick::specificity() masks caret::specificity()\n✖ recipes::step()          masks stats::step()\n✖ data.table::transpose()  masks purrr::transpose()\n• Use suppressPackageStartupMessages() to eliminate package startup messages\n```\n\n\n:::\n:::\n\n\n**incomplete: may contain errors, run-ons, half-thoughts, etc.**\n\n## INTRODUCTION\n\nHemp (Cannabis sativa L.) is an annual crop with potential uses as a source of food or feed from grain, and bast fiber or hurd from the stalk. Hemp cultivars are commonly grown for one or both purposes and a cultivar may be referred to as a grain, fiber, or dual-purpose type. Because of protein's nutritional importance, the protein content of a grain crop is an prime consideration for researchers, producers, and consumers. Whole hemp grain typically contains approximately 20-30% protein [@ely_industrial_2022; @barta_proteomic_2024]. Crude protein (CP) is often used as a proxy for the direct measurement of protein concentration and consists of the multiplication of nitrogen concentration by a conversion factor because measuring nitrogen concentration is relatively easy and cheap via laboratory assay [@hayes_measuring_2020].\n\nNear-infrared spectroscopy (NIRS) technology is rapid, non-destructive, and cheap, and consists of the measurement of NIR radiation reflected from a sample [@roberts_near-infrared_2004]. NIR spectra from many samples are related to laboratory values for components such as moisture, protein, fat, or fiber [@roberts_near-infrared_2004]. NIRS technology has been used since the 1970's to assess forage CP [@reeves_potential_2012; @williams_application_1975]. A NIRS calibration set often consists of samples from one species grown in many environments encompassing the range of expected values from the analyte or analytes [@chadalavada_nir_2022]. Partial least squares regression (PLSR) is a typical method used in the agricultural and food sciences to relate spectra to analyte [@roberts_near-infrared_2004]. PLSR calculates principal components (PCs) which relate to the dependent variable and summarize the spectra and uses a subset of PCs in order to fit the regression model. PLSR is commonly used in spectroscopy because it tends to work well with highly-correlated spectral data. Typically the number of principal components is chosen via cross-validation to avoid overfitting. **CITES FOR ALL OF THIS**\n\nA NIRS-scanned sample of undamaged grain may subsequently be grown, an important consideration for a plant breeder. In wheat and corn, grain protein content has been shown to be heritable [@giancaspro_genetic_2019; @geyer_genetics_2022]. This suggests (at least potentially) that NIRS technology could serve as resource to more rapidly identify high CP hemp germplasm, enabling the delivery of higher CP hemp grain cultivars faster.\n\nFor this study, a benchtop NIR spectrometer was used to develop a model to predict CP content based on a data set of hemp grain representing multiple years, locations, and cultivars from grain and dual-purpose hemp types using PLSR.\n\n## MATERIALS AND METHODS\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nbckgrnd <- fread(\"./input_data/simplified_data/background_data_set.csv\") |> setDT()\n\nspectra <- fread(\"./input_data/simplified_data/train_test_crude_protein.csv\")\n\n bckgrnd[,in_ny:= ifelse(loc!=\"kentucky\", T, F)]\n \nbg2 <- bckgrnd[loc!=\"kentucky\"]\n\n# extract indices of non-kentucky\nbg_indices <- bckgrnd[loc!=\"kentucky\", which = T]\n\n# correct names in bg2--should be h-51, NOT hl-51\n\nbg2[cultivar==\"hl-51\"]$cultivar <- \"h-51\"\n\n# check to see if i did the calc correctly\n\nbg2[grepl(\"51\", cultivar),]\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n   temp_id harv_year       loc cultivar       type  in_ny\n     <int>     <int>    <char>   <char>     <char> <lgcl>\n1:     141      2019 rn041_gen     h-51       dual   TRUE\n2:     149      2019       mcg     h-51 multistate   TRUE\n3:      15      2021    ithaca     h-51 multistate   TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n #looks good \ntab <-  table(bckgrnd$in_ny)\n\n\n# now take correct spectra filtering out stuff from KY\n\nspectra_2 <- spectra[bg_indices]\n```\n:::\n\n\n### Hemp Grain Sample Background\n\nSpectral data were obtained from whole (unground) hemp grain samples, harvested at maturity, collected from 2017 - 2021 from 18 cultivar trials in New York (NY) (149 samples). Grain samples were obtained by hand sampling or mechanical harvest and were cleaned of chaff and dried at 30 C for six days in a forced-air dryer. In total, 38 cultivars were represented in the data set. Cultivars were grain or dual-purpose types and included both commercially available and experimental material.\n\nAll cultivar trials were planted in randomized complete block design with each cultivar replicated four times. The 2017 data were comprised of samples from the same thirteen cultivars sampled from six NY locations. For those trials, grain was harvested from each plot individually and aggregated by cultivar within each trial. Four subsamples were drawn from each aggregated sample and scanned separately. These spectra were averaged at each 2 nm increment. All remaining samples from 2018-2021 were collected on a per-plot basis. All possible cultivars and possible locations were represented in 2017, but only a selected subset of cultivars and locations were represented in 2018-2021.\n\n### Spectral Data Collection and Preprocessing\n\nA benchtop NIR spectrometer (FOSS/ NIR FOSS/ NIR Systems model 5000) was used to obtain the spectra (FOSS North America, Eden Prairie, MN, USA). Spectra were collected every 2 nm from 1100-2498 nm and the logarithm of reciprocal reflectance was recorded.\n\nWINISI software version 1.02A (Infrasoft International, Port Matilda, PA, USA) was used to average the spectra in 2017, as well as to select samples for laboratory assay. Samples were selected according to their spectral distance from their nearest neighbor within the calibration data set with a cutoff of a distance of 0.6 H, where H is approximately equal to the squared Mahalanobis distance divided by the number of principal components used in the calculation [@garrido-varo_note_2019]. Prior to selection selection, spectra were preprocessed using SNV-detrend with settings 1,4,4,1 for the derivative, gap, smooth, and smooth 2 settings respectively.\n\n### Laboratory Validation\n\nLaboratory assays were performed by Dairy One Forage Laboratory (Ithaca, NY). For those assays, 1mm ground samples were analyzed by combustion using a CN628 or CN928 Carbon/Nitrogen Determinator. Samples from 2017 were aggregated as described above, but the remaining samples were not aggregated.\n\n### Model Development\n\nCalibration and validations sets were created by dividing the laboratory CP values into tertiles according to their percent CP in order to ensure that the range of CP values was present in both calibration and validation sets. Within each tertile, 75% of the samples were randomly assigned to the calibration set and the remaining 25% were assigned to the validation set. For each calibration set, models were developed in caret using PLSR. In fitting the model, the number of principal components was optimized over a grid search from 1-20. Model performance was evaluated with a bootstrapping method using root mean squared error (RMSE) and R^2^ statistics in selecting a final model.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\npreproc_key <- fread(\"./input_data/simplified_data/preprocessing_key.csv\")\n\npreproc_key[,full_name:= c(\"Raw Spectra\", \"First Derivative\", \"Savitzky-Golay\", \"Gap-segment derivative\",\n                           \"Standard Normal Variate\", \"Standard Normal Variate/ Savitzky-Golay\", \"SNV-Detrend\", \"Multiplicative Scatter Correction\")]\n```\n:::\n\n\nInitially several of common spectral preprocessing methods were tested by creating 100 calibration and validation sets as described above. Spectral data from those data sets were transformed by each of the following methods: First Derivative, Gap-segment derivative, Multiplicative Scatter Correction, Raw Spectra, Savitzky-Golay, SNV-Detrend, Standard Normal Variate, Standard Normal Variate/ Savitzky-Golay. For each of these preprocessing methods, models were fit and predictions were made on the corresponding validation set (since there were 8 preprocessing methods, 8 separate models were fit for each of the 100 sets. The relationship between the predicted and actual values of validation set were calculated via RMSE, R^2^ and Ratio of Performance to InterQuartile distance (RPIQ). An analysis of variance was performed in order to compare the preprocessing methods according to these metrics considering each data set as a subject, with multiple measurements (preprocessing methods) applied to that subject.\n\nOnce the most promising preprocessing method was identified, 1000 more data sets were created and analyzed via that method and performance on the validation sets summarized with RMSE, R^2^, and RPIQ.\n\n### Additional software used\n\n<!-- Additional analyses were performed using R Statistical Software [@r_core_team_r_2024]. Data were tabulated and summarized using the tidyverse and data.table \\[@barrett_datatable_2024; @wickham_welcome_2019\\]. PLSR models were constructed using the pls package and validated using caret \\[@kuhn_building_2008; @liland_pls_2023\\]. -->\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ngrateful::cite_packages(output = \"paragraph\", out.dir = \".\")\n```\n\n::: {.cell-output-display}\nWe used R version 4.3.3 [@base] and the following R packages: caret v. 6.0.94 [@caret], data.table v. 1.15.2 [@datatable], emmeans v. 1.10.0 [@emmeans], knitr v. 1.45 [@knitr2014; @knitr2015; @knitr2023], lme4 v. 1.1.35.1 [@lme4], pls v. 2.8.3 [@pls], prospectr v. 0.2.7 [@prospectr], randomForest v. 4.7.1.1 [@randomForest], rmarkdown v. 2.26 [@rmarkdown2018; @rmarkdown2020; @rmarkdown2024], skimr v. 2.1.5 [@skimr], tidymodels v. 1.1.1 [@tidymodels], tidyverse v. 2.0.0 [@tidyverse].\n:::\n:::\n\n\n## RESULTS AND DISCUSSION\n\n### Laboratory assay CP values\n\nLaboratory assay percent CP values are summarized in the following table. These are similar to the range of CP values observed in the literature and this indicating an appropriate basis for a chemometric model.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nmy_summary <- spectra_2$crude_protein |> skimr::skim()|> select(c(5:11)) |> \n  mutate_all(round, 1)\nnames(my_summary) <- c(\"mean\", \"sd\", \"minimum\", \"first quartile\", \"median\", \"third quartile\", \"maximum\") \n\nknitr::kable(my_summary, caption = \"Summary of Laboratory Assayed CP values (Values are Percent Dry Matter)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary of Laboratory Assayed CP values (Values are Percent Dry Matter)\n\n| mean|  sd| minimum| first quartile| median| third quartile| maximum|\n|----:|---:|-------:|--------------:|------:|--------------:|-------:|\n| 26.1| 2.5|    20.8|           23.9|   26.4|           28.2|    30.8|\n\n\n:::\n:::\n\n\n### Preprocessing methods comparison\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# \nmulti_metric <- metric_set(rmse, rsq, rpiq,rpd)\n\n\n# read data back in to work with it\n\nprep_key <- fread(\"./input_data/simplified_data/preprocessing_key.csv\")\n\nsims_key <- fread(\"./input_data/simplified_data/preprocessing_methods_test.csv\")\n\nlong_form <- merge(sims_key, prep_key, all.x = T)\n\n# now pull the metrics\n\n# long_form[, multi_metric(y, value), by = c(\"id\", \"preproc\")]\n\nsummaries <- long_form |> \n  group_by(id, preproc) |> \n  multi_metric(y, value)\nhead(summaries)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n     id preproc          .metric .estimator .estimate\n  <int> <chr>            <chr>   <chr>          <dbl>\n1     1 first_derivative rmse    standard        1.15\n2     1 gap_der          rmse    standard        1.31\n3     1 msc              rmse    standard        1.12\n4     1 raw              rmse    standard        1.23\n5     1 sav_gol          rmse    standard        1.19\n6     1 snv              rmse    standard        1.18\n```\n\n\n:::\n:::\n\n\nThis study is limited in that it represents the creation of one model based upon spectra collected from one machine. NIRS calibrations can be unique to a particular machine, if the machines compared are of the same model [@reeves2012]. As well, the calibration and validation sets are relatively small.\n\nThis research showed the promise of the use of NIRS in order to make predictions concerning %CP in hemp grain using PLS. Promising preprocessing methods were identified and a model was validated. Further research could refine the model by including more samples or by examining other predictive methods.\n\n## ACKNOWLEDGMENTS\n\n## SUPPLEMENTAL MATERIAL\n\n## OPTIONAL SECTIONS\n\n## REFERENCES\n\n## FIGURES AND TABLES\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\neruptions <- c(1492, 1585, 1646, 1677, 1712, 1949, 1971, 2021)\nn_eruptions <- length(eruptions)\n```\n:::\n\n::: {#cell-fig-timeline .cell}\n\n```{.r .cell-code .hidden}\npar(mar = c(3, 1, 1, 1) + 0.1)\nplot(eruptions, rep(0, n_eruptions), \n  pch = \"|\", axes = FALSE)\naxis(1)\nbox()\n```\n\n::: {.cell-output-display}\n![Timeline of recent earthquakes on La Palma](index_files/figure-html/fig-timeline-1.png){#fig-timeline fig-alt='An event plot of the years of the last 8 eruptions on La Palma.' width=576}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\navg_years_between_eruptions <- mean(diff(eruptions[-n_eruptions]))\navg_years_between_eruptions\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n[1] 79.83333\n```\n\n\n:::\n:::\n\n\nBased on data up to and including 1971, eruptions on La Palma happen every 79.8 years on average.\n\nStudies of the magma systems feeding the volcano, such as @marrero2019, have proposed that there are two main magma reservoirs feeding the Cumbre Vieja volcano; one in the mantle (30-40km depth) which charges and in turn feeds a shallower crustal reservoir (10-20km depth).\n\nEight eruptions have been recorded since the late 1400s (@fig-timeline).\n\nData and methods are discussed in @sec-data-methods.\n\nLet $x$ denote the number of eruptions in a year. Then, $x$ can be modeled by a Poisson distribution\n\n$$\np(x) = \\frac{e^{-\\lambda} \\lambda^{x}}{x !}\n$$ {#eq-poisson}\n\nwhere $\\lambda$ is the rate of eruptions per year. Using @eq-poisson, the probability of an eruption in the next $t$ years can be calculated.\n\n| Name                | Year |\n|---------------------|------|\n| Current             | 2021 |\n| Teneguía            | 1971 |\n| Nambroque           | 1949 |\n| El Charco           | 1712 |\n| Volcán San Antonio  | 1677 |\n| Volcán San Martin   | 1646 |\n| Tajuya near El Paso | 1585 |\n| Montaña Quemada     | 1492 |\n\n: Recent historic eruptions on La Palma {#tbl-history}\n\n@tbl-history summarises the eruptions recorded since the colonization of the islands by Europeans in the late 1400s.\n\n![Map of La Palma](images/la-palma-map.png){#fig-map}\n\nLa Palma is one of the west most islands in the Volcanic Archipelago of the Canary Islands (@fig-map).\n\n\n{{< embed notebooks/explore-earthquakes.qmd#fig-spatial-plot >}}\n\n\n\n@fig-spatial-plot shows the location of recent Earthquakes on La Palma.\n\n## Data & Methods {#sec-data-methods}\n\n## Conclusion\n\n## References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "index_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}